tagname_Nam_ver1_prompt = """
# Hướng dẫn điền tagnames vào biểu mẫu
Bạn có nhiệm vụ điền các `tagnames` vào biểu mẫu theo định dạng `userX_tagname`.

## 1. Mô tả chung
Tagname là chuỗi đại diện cho một trường thông tin cá nhân, được gán cho một người dùng cụ thể trong biểu mẫu (user1, user2, v.v). Mỗi tagname có định dạng:
`[userX_field_name]`, trong đó:
- `userX`: đại diện cho người dùng thứ X trong biểu mẫu.
- `field_name`: tên trường thông tin như `full_name`, `dob`, `id_number`, `occupation`, ...
Ví dụ:
- `[user1_full_name]`: Họ và tên người điền biểu mẫu.
- `[user2_id_number]`: Số định danh của người được khai báo.
Bạn sẽ được cung cấp:
- Danh sách tagnames kèm mô tả và các mục thường xuất hiện.
- Biểu mẫu gốc với các vị trí cần điền được đánh dấu bằng dấu `..........`.

## 2. Quy tắc điền tagnames
### 2.1. Nguyên tắc chung
- **Không thay đổi nội dung biểu mẫu gốc.** Chỉ điền tagnames vào vị trí có dấu `..........`.
- **Chỉ sử dụng các tagnames được cung cấp.** Không tự ý tạo thêm tagname mới.
- **Đảm bảo đúng người dùng:**
  - `user1_`: Người điền biểu mẫu.
  - `user2_`: Người được khai báo (nếu có).
  - `user3_`, `user4_`: Cha/mẹ (tùy văn cảnh cụ thể).
### 2.2. Cách điền
- Nếu có tagname phù hợp trong danh sách: **Điền đúng tagname vào vị trí tương ứng**.
- Nếu không có tagname phù hợp: **Giữ nguyên `..........`**, không điền gì cả.
### 2.3. Các trường hợp đặc biệt
- **Tên cha/mẹ:**
  Không dùng `[user1_parent_name]`. Phải dùng riêng biệt:
  - Cha: `[user3_full_name]`
  - Mẹ: `[user4_full_name]`
- **Thông tin liên quan đến nước ngoài:**
  Nếu câu hỏi liên quan quốc tịch nước ngoài, nghề nghiệp tại nước ngoài, địa chỉ nước ngoài,… thì **không điền tagname**, để nguyên `..........`.
- **Chỉ điền thông tin hiện tại:**
  Không điền cho thông tin quá khứ hoặc tương lai (VD: nơi cư trú cuối cùng, nơi làm việc cũ,...).
- **Không điền thông tin của doanh nghiệp:**
- **Số CCCD hoặc hộ chiếu:**
  Với các mục như: `Số CCCD/hộ chiếu: ..........` → điền `[user1_id_number]`. (Ưu tiên tagname id_number)
- **Ngành nghề:**
  Dù là “nghề nghiệp”, “nghề nghiệp hiện tại”, “thông tin nghề nghiệp” → dùng `[user1_occupation]`.
  Tuy nhiên, KHÔNG điền `[user1_occupation]` nếu:
  - Câu chỉ nói đến nơi làm việc mà không nói nghề cụ thể.
    *Ví dụ sai:* “Công tác tại: Công ty ABC” → không điền occupation.
  - Câu đề cập đến tình trạng thất nghiệp.
  - Câu nói về bệnh nghề nghiệp.
- **Năm sinh:** sử dụng tagname [dob_year]
- **Giấy tờ tùy thân:** Sử dụng tagname [id_number]

## 3. Định dạng đầu vào và đầu ra
### Input:
- **Danh sách tagnames** (bao gồm mô tả, ví dụ, và các cụm từ thường gặp).
- **Biểu mẫu gốc**, các vị trí cần điền được đánh dấu bằng `..........`.
### Output:
- **Biểu mẫu đã điền tagname** chính xác vào từng vị trí `..........` theo các nguyên tắc trên.

## Ví dụ:
Input:
```
TỜ KHAI CĂN CƯỚC CÔNG DÂN
1. Họ, chữ đệm và tên(1): ..........
Ngày sinh: ..........
Ngày sinh viết bằng chữ: ..........
Năm sinh: ..........
3. Ngày, tháng, năm sinh: ........../........../..........; 4. Giới tính (Nam/nữ): ..........
5. Số CMND: ..........  CCCD: ..........
6. Dân tộc: ..........; 7. Tôn giáo: .......... 8. Quốc tịch: ..........
9. Tình trạng hôn nhân: .......... 10. Nhóm máu (nếu có): ..........
Số điện thoại bàn: ..........
11. Nơi đăng ký khai sinh: ..........
12. Quê quán: ..........
13. Nơi thường trú: ..........
14. Nơi ở hiện tại: ..........
15. Nghề nghiệp: .......... 16. Trình độ học vấn: ..........
.........., ngày ..........tháng..........năm..........
```
Output:
```
TỜ KHAI CĂN CƯỚC CÔNG DÂN
1. Họ, chữ đệm và tên(1): [user1_full_name]
Ngày sinh: [user1_dob]
Ngày sinh viết bằng chữ: [user1_dob_text]
Năm sinh: [user1_dob_year]
3. Ngày, tháng, năm sinh: [user1_dob_day]/[user1_dob_month]/[user1_dob_year]; 4. Giới tính (Nam/nữ): [user1_gender]
5. Số CMND: [user1_id_number]  CCCD: [user1_id_number]
6. Dân tộc: [user1_ethnicity]; 7. Tôn giáo: [user1_religion] 8. Quốc tịch: [user1_nationality]
9. Tình trạng hôn nhân: [user1_marital_status] 10. Nhóm máu (nếu có): [user1_blood_type]
Số điện thoại bàn: [user1_home_phone]
11. Nơi đăng ký khai sinh: [user1_birth_registration_place]
12. Quê quán: [user1_hometown]
13. Nơi thường trú: [user1_permanent_address]
14. Nơi ở hiện tại: [user1_current_address]
15. Nghề nghiệp: [user1_occupation] 16. Trình độ học vấn: [user1_education_level]
.........., ngày .......... tháng .......... năm ..........
```

## Ví dụ:
Input:
```
TỜ KHAI THAY ĐỔI THÔNG TIN CƯ TRÚ
(Dùng cho công dân Việt Nam định cư ở nước ngoài
không có hộ chiếu Việt Nam còn giá trị sử dụng)

Kính gửi (1):..........
1. Họ, chữ đệm và tên Việt Nam:..........
2. Họ, chữ đệm và tên trong hộ chiếu/giấy tờ do nước ngoài cấp:	..........
3. Ngày, tháng, năm sinh:........../........../ .......... Viết bằng chữ: ..........     4. Giới tính:..........
5. Dân tộc:..........     6. Tôn giáo:..........
7. Số định danh cá nhân/CMND: ..........
8. Số điện thoại (nếu có):.......... Số điện thoại cố định: ..........	 9. E-mail (nếu có):..........
10. Quốc tịch nước ngoài (nếu có):..........
11. Số hộ chiếu/ Giấy tờ đi lại quốc tế do nước ngoài cấp/ Giấy tờ do cơ quan có thẩm quyền Việt Nam cấp:
Số:	.......... Ngày cấp: ........../........../..........
Cơ quan cấp:..........	 Có giá trị đến ngày:........../........../..........
Ngày hết hạn hộ chiếu: ..........
12. Nghề nghiệp, nơi làm việc ở nước ngoài trước khi nhập cảnh Việt Nam:..........
13. Họ, chữ đệm và tên, năm sinh, quốc tịch, nghề nghiệp, nơi làm việc, chỗ ở hiện nay của cha, mẹ, vợ, chồng, con:..........
14. Nơi cư trú ở nước ngoài trước khi nhập cảnh Việt Nam:..........
15. Nơi ở hiện tại ở Việt Nam:..........
16. Nội dung đề nghị (2):..........
17. Họ và tên chủ hộ:..........18. Quan hệ với chủ hộ:..........
19. Số định danh cá nhân/ CMND của chủ hộ:..........
20. Tên cha mẹ: ..........
```
Output:
```
TỜ KHAI THAY ĐỔI THÔNG TIN CƯ TRÚ
(Dùng cho công dân Việt Nam định cư ở nước ngoài
không có hộ chiếu Việt Nam còn giá trị sử dụng)

Kính gửi (1): ..........
1. Họ, chữ đệm và tên Việt Nam: [user1_full_name]
2. Họ, chữ đệm và tên trong hộ chiếu/giấy tờ do nước ngoài cấp:	..........
3. Ngày, tháng, năm sinh: [user1_dob_day]/[user1_dob_month]/[user1_dob_year] Viết bằng chữ: [user1_dob_text]    4. Giới tính: [user1_gender]
5. Dân tộc: [user1_ethnicity]     6. Tôn giáo: [user1_religion]
7. Số định danh cá nhân/CMND: [user1_id_number]
8. Số điện thoại (nếu có): [user1_phone]	Số điện thoại cố định: [user1_home_phone] 9. E-mail (nếu có): [user1_email]
10. Quốc tịch nước ngoài (nếu có): ..........
11. Số hộ chiếu/ Giấy tờ đi lại quốc tế do nước ngoài cấp/ Giấy tờ do cơ quan có thẩm quyền Việt Nam cấp:
Số:	[user1_passport_number] Ngày cấp: [user1_passport_issue_day]/[user1_passport_issue_month]/[user1_passport_issue_year]
Cơ quan cấp: [user1_passport_issue_place]	 Có giá trị đến ngày: [user1_passport_expiry_day]/[user1_passport_expiry_month]/[user1_passport_expiry_year]
Ngày hết hạn hộ chiếu: [user1_passport_expiry_date]
12. Nghề nghiệp, nơi làm việc ở nước ngoài trước khi nhập cảnh Việt Nam: ..........
13. Họ, chữ đệm và tên, năm sinh, quốc tịch, nghề nghiệp, nơi làm việc, chỗ ở hiện nay của cha, mẹ, vợ, chồng, con: ..........
14. Nơi cư trú ở nước ngoài trước khi nhập cảnh Việt Nam: ..........
15. Nơi ở hiện tại ở Việt Nam: [user1_current_address]
16. Nội dung đề nghị (2): ..........
17. Họ và tên chủ hộ: [user2_full_name] 18. Quan hệ với chủ hộ: ..........
19. Số định danh cá nhân/ CMND của chủ hộ: [user2_id_number]
20. Tên cha mẹ: [user3_full_name]
```

## Ví dụ:
Input:
```
Tờ khai thông tin
Kính gửi: ..........
1. Họ .......... chữ đệm và tên: ..........
Tên gọi khác: ..........
2. Ngày sinh: ..........
Bằng chữ: ..........
Năm sinh: ..........
Giấy tờ tùy thân: ..........
3. Nơi ở hiện tại:
Thôn/bản: .......... Xã/phường: ..........
Quận/Huyện: .......... Tỉnh/thành phố: ..........
4. Nơi thường trú:
Thôn/bản: .......... Xã/phường: ..........
Quận/Huyện: .......... Tỉnh/thành phố: ..........
5. Nơi sinh:
Xã/phường: .......... Quận/Huyện: .......... Tỉnh/thành phố: ..........
6. Nơi đăng ký khai sinh/Nơi làm giấy khai sinh:
Xã/phường: .......... Quận/Huyện: .......... Tỉnh/thành phố: ..........
7. Quê quán/nguyên quán: ..........
8. Số điện thoại: .......... Số cố định/bàn: ..........
9. Số BHYT/Bảo hiểm y tế: ..........
10. Số BHXH/bảo hiểm xã hội: ..........
```
Output:
```
Tờ khai thông tin
Kính gửi: ..........
1. Họ [user1_last_name] chữ đệm và tên: [user1_middle_and_first_name]
Tên gọi khác: [user1_alias_name]
2. Ngày sinh: [user1_dob]
Bằng chữ: [user1_dob_text]
Năm sinh: [user1_dob_year]
Giấy tờ tùy thân: [user1_id_number]
3. Nơi ở hiện tại/tạm trú:
Thôn/bản: [user1_current_address_village] Xã/phường: [user1_current_address_ward]
Quận/Huyện: [user1_current_address_district] Tỉnh/thành phố: [user1_current_address_province]
4. Nơi thường trú:
Thôn/bản: [user1_permanent_address_village] Xã/phường: [user1_permanent_address_ward]
Quận/Huyện: [user1_permanent_address_district] Tỉnh/thành phố: [user1_permanent_address_province]
5. Nơi sinh:
Xã/phường: [user1_birthplace_ward] Quận/Huyện: [user1_birthplace_district] Tỉnh/thành phố: [user1_birthplace_province]
6. Nơi đăng ký khai sinh/Nơi làm giấy khai sinh:
Xã/phường: [user1_birth_registration_ward] Quận/Huyện: [user1_birth_registration_district] Tỉnh/thành phố: [user1_birth_registration_province]
7. Quê quán/nguyên quán: [user1_hometown]
8. Số điện thoại: [user1_phone] Số cố định/bàn: [user1_home_phone]
9. Số BHYT/Bảo hiểm y tế: [user1_health_insurance_number]
10. Số BHXH/bảo hiểm xã hội: [user1_social_insurance_number]
```

## Ví dụ:
Input:
```
Tờ khai thông tin
Số: ..........
Kính gửi: ..........
Thành viên 1
1. Họ và tên: ..........
2. Số CCCD: ..........
Ngày cấp: ..........
Cấp ngày: ........../........../..........
Nơi cấp: ..........
3. Số hộ chiếu/passport: ..........
Ngày cấp: ........../........../..........
Cấp ngày: ..........
Nơi cấp: ..........
4. Ngày hết hạn hộ chiếu: ..........
Hộ chiếu hết hạn ngày: .......... tháng .......... năm ..........
Thành viên 2
Họ: .......... chữ đệm và tên: ..........
1. Ngày sinh: ..........
2. Nơi sinh: ..........
3. Nơi đăng ký khai sinh: ..........
4. Năm sinh: ..........

Ngày làm đơn: .......... tháng .......... năm ..........
```
Output:
```
Tờ khai thông tin
Số: ..........
Kính gửi: ..........
Thành viên 1
1. Họ và tên: [user1_full_name]
2. Số CCCD: [user1_id_number]
Ngày cấp: [user1_id_issue_date]
Cấp ngày: [user1_id_issue_day]/[user1_id_issue_month]/[user1_id_issue_year]
Nơi cấp: [user1_id_issue_place]
3. Số hộ chiếu/passport: [user1_passport_number]
Ngày cấp: [user1_passport_issue_day]/[user1_passport_issue_month]/[user1_passport_issue_year]
Cấp ngày: [user1_passport_issue_date]
Nơi cấp: [user1_passport_issue_place]
4. Ngày hết hạn hộ chiếu: [user1_passport_expiry_date]
Hộ chiếu hết hạn ngày: [user1_passport_expiry_day] tháng [user1_passport_expiry_month] năm [user1_passport_expiry_year]
Thành viên 2
Họ: [user2_lastname] chữ đệm và tên: [user2_middle_and_first_name]
1. Ngày sinh: [user2_dob]
2. Nơi sinh: [user2_birthplace]
3. Nơi đăng ký khai sinh: [user2_birth_registration_place]
4. Năm sinh: [user2_dob_year]

Ngày làm đơn: .......... tháng .......... năm ..........
```

## Ví dụ:
Input:
```
{form}
```
Ouput:
"""