# Inference to fill tagname to string form
from Config.LLM import gemini
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from Prompts.define_tagnames import tagname_Nam_ver1_prompt
from Config.tagnames import tagname_Nam_ver1
def define_tagname_Nam_ver1(llm, text):
    prompt = PromptTemplate.from_template(tagname_Nam_ver1_prompt)
    chain = prompt | llm | StrOutputParser()
    
    response = chain.invoke(
        {"tagname": tagname_Nam_ver1, "form": text}
    )
    return response


string_form = """
Kính gửi: tỉnh/thành phố ..........
họ và tên: ..........
số điện thoại cố định: ..........
Số tài khoản: ..........
Hệ đào tạo: ..........
Quan hệ: ..........
thôn/bản nơi thường trú: ..........
Khoa: ..........
nơi sinh: ..........
Nơi đăng ký khám bệnh: ..........
phường/xã nơi sinh: ..........
trình độ học vấn: ..........
ngày sinh đầy đủ: ..........
ngày cấp hộ chiếu: ngày .......... tháng .......... năm ..........
tỉnh/thành nơi cư trú: ..........
phường/xã đăng ký khai sinh: ..........
Thời gian mai táng: ..........
Mã số sinh viên: ..........
Học kì: ..........
Nội dung yêu cầu giải quyết: ..........
tỉnh/thành nơi sinh: ..........
Nguyên nhân: ..........
quận/huyện nơi thường trú: ..........
Trường học: ..........
Quyết định số: ..........
họ: ..........
công việc hiện tại: ..........
chỗ ở hiện tại: ..........
số định danh: ..........
Lớp học hiện tại: ..........
quận/huyện nơi sinh: ..........
quận/huyện nơi ở: ..........
năm sinh: ..........
Năm học: ..........
"""

# Inference to fill tagname to string form
llm_filled = define_tagname_Nam_ver1(gemini, string_form)
while not llm_filled.strip():  # Check if empty or contains only whitespace
    llm_filled = define_tagname_Nam_ver1(gemini, string_form)

print("Generated successfully!!")
print(llm_filled)